@baseUrl = http://localhost:3333/api

### Create a new production server
POST   {{baseUrl}}/products
{
  "image": "url_da_imagem",
  "description": "Descrição do sprodus5sto",
  "code": "CODs1243",
  "ean": "789012s34456s789",
  "supplier": "64f0a5bd8669d873788b76d6",
  "manufacturer": "Fabricante XYZ",
  "quantity": 100,
  "replacementUnit": "unidade",
  "conversionFactor": 1,
  "infoPrice": {
    "wholesalePrice": 50.0,
    "retailPrice": 70.0,
    "posPrice": 60.0
  },
  "infoProduct": {
    "weightUnit": "kg",
    "netWeight": 1.5,
    "grossWeight": 2.0,
    "shelfLife": 365,
    "height": 10.0,
    "width": 5.0,
    "depth": 2.0,
    "volume": 100.0,
    "length": 15.0
  },
  "infoLogistics": {
    "layersPerPallet": 5,
    "rowsPerPallet": 10,
    "packagingQuantityPerPallet": 50
  }
}
### list proucts
GET {{baseUrl}}/products?query=&supplie=64f0a5bd8669d873788b76d6

