@baseUrl = http://localhost:3333/api

### Create a new production server
POST   {{baseUrl}}/products
{
  "image": "url_da_imassgem",
  "description": "Descriçãoss do sprodus5sto",
  "code": "CODss1243",
  "ean": "789012ss34456s789",
  "supplier": "64f0a5bd8669d873788b76d6",
  "manufacturer": "Fabricante XYZ",
  "quantity": "125",
  "replacementUnit": "unidade",
  "conversionFactor": "",
  "infoPrice": {
    "wholesalePrice": "50",
    "retailPrice": "",
    "posPrice": ""
  },
  "infoProduct": {
    "weightUnit": "kg",
    "netWeight": "",
    "grossWeight": "",
    "shelfLife": "",
    "height": "",
    "width": "",
    "depth": "",
    "volume": "",
    "length": ""
  },
  "infoLogistics": {
    "layersPerPallet": "",
    "rowsPerPallet": "",
    "packagingQuantityPerPallet": ""  }
}
### list proucts
GET {{baseUrl}}/products?query=&supplie=64f0a5bd8669d873788b76d6

